# Challenge 1

In this challenge you will be working on **Pokemon**. You will answer a series of questions in order to practice dataframe calculation, aggregation, and transformation.

![Pokemon](../images/pokemon.jpg)

Follow the instructions below and enter your code.

#### Import all required libraries.

In [1]:
# import libraries
import pandas as pd
import numpy as np

#### Import data set.

Read the dataset `pokemon.csv` into a dataframe called `pokemon`.

*Data set attributed to [Alberto Barradas](https://www.kaggle.com/abcsds/pokemon/)*

In [2]:
# import dataset
pokemon_df = pd.read_csv("Pokemon.csv")

#### Print first 10 rows of `pokemon`.

In [3]:
# your code here
pokemon_df.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

When you look at a data set, you often wonder what each column means. Some open-source data sets provide descriptions of the data set. In many cases, data descriptions are extremely useful for data analysts to perform work efficiently and successfully.

For the `Pokemon.csv` data set, fortunately, the owner provided descriptions which you can see [here](https://www.kaggle.com/abcsds/pokemon/home). For your convenience, we are including the descriptions below. Read the descriptions and understand what each column means. This knowledge is helpful in your work with the data.

| Column | Description |
| --- | --- |
| # | ID for each pokemon |
| Name | Name of each pokemon |
| Type 1 | Each pokemon has a type, this determines weakness/resistance to attacks |
| Type 2 | Some pokemon are dual type and have 2 |
| Total | A general guide to how strong a pokemon is |
| HP | Hit points, or health, defines how much damage a pokemon can withstand before fainting |
| Attack | The base modifier for normal attacks (eg. Scratch, Punch) |
| Defense | The base damage resistance against normal attacks |
| SP Atk | Special attack, the base modifier for special attacks (e.g. fire blast, bubble beam) |
| SP Def | The base damage resistance against special attacks |
| Speed | Determines which pokemon attacks first each round |
| Generation | Number of generation |
| Legendary | True if Legendary Pokemon False if not |

#### Obtain the distinct values across `Type 1` and `Type 2`.

Exctract all the values in `Type 1` and `Type 2`. Then create an array containing the distinct values across both fields.

In [4]:
pokemon_df.shape

(800, 13)

In [5]:
pokemon_df["Type 1"]

0        Grass
1        Grass
2        Grass
3        Grass
4         Fire
        ...
795       Rock
796       Rock
797    Psychic
798    Psychic
799       Fire
Name: Type 1, Length: 800, dtype: object

In [6]:
pokemon_df['Type 2']

0      Poison
1      Poison
2      Poison
3      Poison
4         NaN
        ...
795     Fairy
796     Fairy
797     Ghost
798      Dark
799     Water
Name: Type 2, Length: 800, dtype: object

In [7]:
# your code here
pokemon_df_unique = pd.unique(pokemon_df[['Type 1', 'Type 2']].values.ravel())
display(pokemon_df_unique)

array(['Grass', 'Poison', 'Fire', nan, 'Flying', 'Dragon', 'Water', 'Bug',
       'Normal', 'Electric', 'Ground', 'Fairy', 'Fighting', 'Psychic',
       'Rock', 'Steel', 'Ice', 'Ghost', 'Dark'], dtype=object)

#### Cleanup `Name` that contain "Mega".

If you have checked out the pokemon names carefully enough, you should have found there are junk texts in the pokemon names which contain "Mega". We want to clean up the pokemon names. For instance, "VenusaurMega Venusaur" should be "Mega Venusaur", and "CharizardMega Charizard X" should be "Mega Charizard X".

In [8]:
# your code here
import re
def clean_single_pokemon_name(name):
    # Use regular expression to remove any prefix containing "Mega"
    return re.sub(r'\w*Mega ', 'Mega ', name)

# Apply the cleaning function to the "Pokemon_Name" column
pokemon_df['Name'] = pokemon_df['Name'].apply(clean_single_pokemon_name)

pokemon_df


# def clean_pokemon_name(Name):
#     for name in pokemon_df['Name']:
#         if name.__contains__('Mega' | ): 
#             name_split = name.split('Mega')
#             new_name = 'Mega' + ' ' + name_split.pop(0)  
#     return(new_name)

# pokemon_df.apply(clean_pokemon_name)

# pokemon_df.sample(30)


# string = 'VenusaurMega Venusaur'
# string_2 = string.split('Mega')
# string_3 = 'Mega' + ' ' + string_2.pop(0) 
# string_3


# test transformed data
#pokemon_df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,Mega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

#### Create a new column called `A/D Ratio` whose value equals to `Attack` devided by `Defense`.

For instance, if a pokemon has the Attack score 49 and Defense score 49, the corresponding `A/D Ratio` is 49/49=1.

In [9]:
# your code here
pokemon_df['A/D Ratio'] = round(pokemon_df['Attack'] / pokemon_df['Defense'])
pokemon_df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.0
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,1.0
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,1.0
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,1.0
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,1.0
796,719,Mega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,1.0
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,2.0
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,3.0
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,1.0

#### Identify the pokemon with the highest `A/D Ratio`.

In [10]:
# your code here
#pokemon_df[pokemon_df.Name == np.max(pokemon_df['A/D Ratio'])]

pokemon_df[pokemon_df['A/D Ratio'] == np.max(pokemon_df['A/D Ratio'])]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.0

#### Identify the pokemon with the lowest A/D Ratio.

In [11]:
# your code here
pokemon_df[pokemon_df['A/D Ratio'] == np.min(pokemon_df['A/D Ratio'])]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
14,11,Metapod,Bug,NaN,205,50,20,55,25,25,30,1,False,0.0
17,14,Kakuna,Bug,Poison,205,45,25,50,25,25,35,1,False,0.0
87,80,Mega Slowbro,Water,Psychic,590,95,75,180,130,80,30,1,False,0.0
88,81,Magnemite,Electric,Steel,325,25,35,70,95,55,45,1,False,0.0
103,95,Onix,Rock,Ground,385,35,45,160,30,45,70,1,False,0.0
110,102,Exeggcute,Grass,Psychic,325,60,40,80,60,45,40,1,False,0.0
122,114,Tangela,Grass,NaN,435,65,55,115,100,40,60,1,False,0.0
139,129,Magikarp,Water,NaN,200,20,10,55,15,20,80,1,False,0.0
149,138,Omanyte,Rock,Water,355,35,40,100,90,55,35,1,False,0.0
150,139,Omastar,Rock,Water,495,70,60,125,115,70,55,1,False,0.0
189,175,Togepi,Fairy,NaN,245,35,20,65,40,65,20,2,False,0.0
190,176,Togetic,Fairy,Flying,405,55,40,85,80,105,40,2,False,0.0
198,183,Marill,Water,Fairy,250,70,20,50,20,50,40,2,False,0.0
223,208,Steelix,Steel,Ground,510,75,85,200,55,65,30,2,False,0.0
230,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False,0.0
237,219,Magcargo,Fire,Rock,410,50,50,120,80,80,30,2,False,0.0
302,279,Pelipper,Water,Flying,430,60,50,100,85,70,65,3,False,0.0
314,290,Nincada,Bug,Ground,266,31,45,90,30,30,40,3,False,0.0
322,298,Azurill,Normal,Fairy,190,50,20,40,20,40,20,3,False,0.0
323,299,Nosepass,Rock,NaN,375,30,45,135,45,90,30,3,False,0.0
388,355,Duskull,Ghost,NaN,295,20,40,90,30,90,25,3,False,0.0
394,360,Wynaut,Psychic,NaN,260,95,23,48,23,48,23,3,False,0.0
414,377,Regirock,Rock,NaN,580,80,100,200,50,100,50,3,True,0.0
415,378,Regice,Ice,NaN,580,80,50,100,100,200,50,3,True,0.0
416,379,Registeel,Steel,NaN,580,80,75,150,75,150,50,3,True,0.0
430,386,DeoxysDefense Forme,Psychic,NaN,600,50,70,160,70,160,90,3,True,0.0
455,410,Shieldon,Rock,Steel,350,30,42,118,42,88,30,4,False,0.0
456,411,Bastiodon,Rock,Steel,495,60,52,168,47,138,30,4,False,0.0
484,436,Bronzor,Steel,Psychic,300,57,24,86,24,86,23,4,False,0.0
508,458,Mantyke,Water,Flying,345,45,20,50,60,120,50,4,False,0.0
528,476,Probopass,Rock,Steel,525,60,55,145,75,150,40,4,False,0.0
591,531,Mega Audino,Normal,Fairy,545,103,60,126,80,126,50,5,False,0.0
606,546,Cottonee,Grass,Fairy,280,40,27,60,37,50,66,5,False,0.0
616,555,DarmanitanZen Mode,Fire,Psychic,540,105,30,105,140,105,55,5,False,0.0
623,562,Yamask,Ghost,NaN,303,38,30,85,55,65,30,5,False,0.0
624,563,Cofagrigus,Ghost,NaN,483,58,50,145,95,105,30,5,False,0.0
677,616,Shelmet,Bug,NaN,305,50,40,85,40,65,25,5,False,0.0
733,665,Spewpa,Bug,NaN,213,45,22,60,27,30,29,6,False,0.0
751,681,AegislashShield Forme,Steel,Ghost,520,60,50,150,50,150,60,6,False,0.0
773,703,Carbink,Rock,Fairy,500,50,50,150,50,150,50,6,False,0.0

#### Create a new column called `Combo Type` whose value combines `Type 1` and `Type 2`.

Rules:

* If both `Type 1` and `Type 2` have valid values, the `Combo Type` value should contain both values in the form of `<Type 1> <Type 2>`. For example, if `Type 1` value is `Grass` and `Type 2` value is `Poison`, `Combo Type` will be `Grass-Poison`.

* If `Type 1` has valid value but `Type 2` is not, `Combo Type` will be the same as `Type 1`. For example, if `Type 1` is `Fire` whereas `Type 2` is `NaN`, `Combo Type` will be `Fire`.

In [12]:
# your code here
def pokemon_combo_type(row):
    type1 = row['Type 1']
    type2 = row['Type 2']
    
    if pd.notna(type2):
        return f"{type1}-{type2}"
    else:
        return type1

pokemon_df['Combo Type'] = pokemon_df.apply(pokemon_combo_type, axis=1)


pokemon_df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.0,Grass-Poison
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,1.0,Grass-Poison
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,1.0,Grass-Poison
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,1.0,Grass-Poison
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1.0,Fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,1.0,Rock-Fairy
796,719,Mega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,1.0,Rock-Fairy
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,2.0,Psychic-Ghost
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,3.0,Psychic-Dark
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,1.0,Fire-Water

#### Identify the pokemon whose `A/D Ratio` are among the top 5.

In [13]:
# your code here
top_5_pokemon = pokemon_df.sort_values(by='A/D Ratio', ascending=False).head(5)

top_5_pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.0,Psychic
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,4.0,Water-Dark
19,15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,4.0,Bug-Poison
750,681,AegislashBlade Forme,Steel,Ghost,520,60,150,50,150,50,60,6,False,3.0,Steel-Ghost
186,172,Pichu,Electric,NaN,205,20,40,15,35,35,60,2,False,3.0,Electric

#### For the 5 pokemon printed above, aggregate `Combo Type` and use a list to store the unique values.

Your end product is a list containing the distinct `Combo Type` values of the 5 pokemon with the highest `A/D Ratio`.

In [14]:
# your code here
unique_values_combo_type = [top_5_pokemon['Combo Type'].unique()]
unique_values_combo_type

[array(['Psychic', 'Water-Dark', 'Bug-Poison', 'Steel-Ghost', 'Electric'],
       dtype=object)]

#### For each of the `Combo Type` values obtained from the previous question, calculate the mean scores of all numeric fields across all pokemon.

Your output should look like below:

![Aggregate](../images/aggregated-mean.png)

In [15]:
pokemon_df.dtypes

#               int64
Name           object
Type 1         object
Type 2         object
Total           int64
HP              int64
Attack          int64
Defense         int64
Sp. Atk         int64
Sp. Def         int64
Speed           int64
Generation      int64
Legendary        bool
A/D Ratio     float64
Combo Type     object
dtype: object

In [21]:
# your code here
numeric_columns = top_5_pokemon.select_dtypes(include='number')
combo_type_means_top_5 = top_5_pokemon.groupby('Combo Type')[numeric_columns.columns].mean()
combo_type_means_top_5

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,A/D Ratio
Combo Type,,,,,,,,,,
Bug-Poison,15.0,495.0,65.0,150.0,40.0,15.0,80.0,145.0,1.0,4.0
Electric,172.0,205.0,20.0,40.0,15.0,35.0,35.0,60.0,2.0,3.0
Psychic,386.0,600.0,50.0,180.0,20.0,180.0,20.0,150.0,3.0,9.0
Steel-Ghost,681.0,520.0,60.0,150.0,50.0,150.0,50.0,60.0,6.0,3.0
Water-Dark,318.0,305.0,45.0,90.0,20.0,65.0,20.0,65.0,3.0,4.0